### ISSUE TITLE
咸鱼？

### ISSUE THREAD

**Issue by kajweb** [lixi5338619/lxSpider#1]

**Comment by lixi5338619** [comment]
什么咸鱼，是指咸鱼app吗 ？

**Comment by kajweb** [comment]
yes

**Comment by lixi5338619** [comment]
目前还没有写过这个，我抽空写个案例发上来

**Comment by kajweb** [comment]
thanks

**Comment by kajweb** [comment]
想了解一下，咸鱼app爬虫难度如何

**Comment by lixi5338619** [comment]
> 想了解一下，咸鱼app爬虫难度如何

有难度的，我上次简单看了一下，目前关闭了web端，app数据也没有用http协议。

**Comment by lixi5338619** [comment]
> 想了解一下，咸鱼app爬虫难度如何

除了分析app源码，想降低采集难度的话，可以使用自动化工具或者数据拦截转发的方式。

**Comment by lixi5338619** [comment]
闲鱼抓包案例，用frida去hook掉Spdy实现抓包。

https://blog.csdn.net/weixin_43582101/article/details/114667690
